name: Terraform GKE

on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform plan -out=tfplan && terraform apply -auto-approve tfplan
  


