name: Terraform GKE

on:
 workflow_dispatch: 
     inputs:
       action:
           description: 'Choosing whether to apply or destroy the infra'
           required: true
           default: 'apply' 
           type: choice
           options:
              - apply
              - destroy
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure GCP credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run:  terraform apply --auto-approve tfplan

      - name: Terraform Destroy 
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy --auto-approve

